[package]
name = "pontus_onyx"
version = "0.2.0"
authors = ["Jimskapt <rami.programmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client"]
all = ["client", "server"]
client = []
server = ["actix-web", "actix-rt", "serde_json", "futures", "env_logger", "regex", "rand", "hmac-sha512", "zeroize", "toml", "derivative"]

[dependencies]
serde = { version = "^1", features = ["derive"] }
ulid = { version = "^0", features = ["serde"] }
chrono = { version = "^0", features = ["serde"] }
percent-encoding = "^2"
bincode = "^1"


serde_json = { version = "^1", optional = true }
actix-web = { version = "^3", optional = true }
actix-rt = { version = "^2", optional = true }
futures = { version = "^0", optional = true }
env_logger = { version = "^0", optional = true }
regex = { version = "^1", optional = true }
rand = { version = "^0", optional = true }
hmac-sha512 = { version = "^0", optional = true }
zeroize = { version = "^1", optional = true }
toml = { version = "^0", optional = true }
derivative = { version = "^2", optional = true }
