[package]
name = "pontus_onyx"
description = "A remoteStorage server and client library"
keywords = ["remotestorage", "database", "local-first", "http", "rest"]
categories = ["database", "database-implementations", "web-programming", "wasm"]
documentation = "https://docs.rs/pontus_onyx/"

[package.version]
workspace = true

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.license]
workspace = true

[package.readme]
workspace = true

[package.repository]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
rand = "0.8.5"
regex = "1.10.6"
async-trait = "0.1.81"
derivative = "2.2.0"
anyhow = "1.0.86"
time = { version = "0.3.36", features = ["serde", "wasm-bindgen"] }
serde = { version = "1.0.204", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v4"] }
zeroize = { version = "1.8.1", features = ["derive"] }
tokio = { version = "1.39.2", features = ["rt", "macros"] }

actix-web = { version = "4.8.0", optional = true }
futures-core = { version = "0.3.30", optional = true }
serde_json = { version = "1.0.122", optional = true }
actix-http = { version = "3.8.0", optional = true }
serde-encrypt = "0.7.0"

[features]
actix_server = ["dep:actix-web", "dep:actix-http", "dep:futures-core", "dep:serde_json"]
